name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t falcon9_image .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker tag falcon9_image ${{ secrets.DOCKER_USERNAME }}/falcon9_image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/falcon9_image:latest

      - name: Deploy to server
        run: |
          docker stop spacex_container || true
          docker rm spacex_container || true
          docker run -d -p 5000:80 --name spacex_container ${{ secrets.DOCKER_USERNAME }}/falcon9_image:latest
